version: '3.9'
volumes:
  mongo:
services:
  cache:
    container_name: trader_redis
    image: redis
    ports:
      - 6379:6379
  database:
    container_name: trader_database
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo:/data/db