name: Build and deploy

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Set up zone GCP
      run: gcloud config set compute/zone ${{ secrets.GCP_REGION }}

    - name: Authorize Docker
      run: gcloud auth configure-docker
    
    - name: Build and push to GCR
      run: |-
        docker build -t asia.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA -t asia.gcr.io/$PROJECT_ID/$SERVICE_NAME:latest .
        docker push asia.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

    - name: Deploy to GCE
      run: |-
        gcloud compute ssh $SERVICE_NAME
        docker system prune -f -a

    - name: Run container
      run: docker run -d \
        -p ${{ secrets.PORT }}:${{ secrets.PORT }} \
        --name $SERVICE_NAME \
        --restart always \
        -e HOST=${{ secrets.HOST }} \
        -e PORT=${{ secrets.PORT }} \
        -e SESSION_COOKIE_SECRET=${{ secrets.SESSION_COOKIE_SECRET }} \
        -e DB_URI=${{ secrets.DB_URI }} \
        -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
        -e DB_PASSWORD=${{ secrets.DB_PASSWORD}} \
        -e DB_NAME=${{ secrets.DB_NAME }} \
        -e STEAM_OPENID_IDENTIFIER=${{ secrets.STEAM_OPENID_IDENTIFIER }} \
        -e STEAM_OPENID_REALM=${{ secrets.STEAM_OPENID_REALM }} \
        -e STEAM_OPENID_REALM=${{ secrets.STEAM_OPENID_REALM }} \
        -e STEAM_API_URL=${{ secrets.STEAM_API_URL }} \
        -e STEAM_API_KEY=${{ secrets.STEAM_API_KEY }} \
        -e ETOP_API_URL=${{ secrets.ETOP_API_URL }} \
        -e ETOP_EMAIL=${{ secrets.ETOP_EMAIL }} \
        -e ETOP_PASSWORD=${{ secrets.ETOP_PASSWORD }} \
        -e ETOP_APP_ID=${{ secrets.ETOP_APP_ID }} \
        -e ETOP_HOT_VERSION=${{ secrets.ETOP_HOT_VERSION }} \
        asia.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA